# --------- Theme ---------
include current-theme.conf

# --------- Fonts ---------
font_family        Caskaydia Cove Nerd Font
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size          11.0
disable_ligatures  never

# --------- Cursor & Mouse ---------
cursor_shape           block
cursor_blink_interval  0
mouse_hide_wait        3.0
url_style              curly
detect_urls            yes
copy_on_select         no

# --------- Window ---------
background_opacity       0.9
background_blur          1
window_padding_width     4
enable_audio_bell        no
hide_window_decorations  yes
confirm_os_window_close  0

# -------- Window Tab ----------
tab_bar_min_tabs           1
tab_bar_edge               bottom
tab_bar_background         none
tab_bar_style              powerline
tab_bar_align              left
tab_switch_strategy        left
tab_title_template         "{index}: {title}"
active_tab_title_template  "{index}: {title}"
active_tab_foreground      #fff
active_tab_background      #79A1F6
active_tab_font_style      bold-italic
inactive_tab_foreground    #c2c2c2
inactive_tab_background    #333852
inactive_tab_font_style    normal

# --------- Sessions ---------
enabled_layouts        splits,stack

# -------- Shortcuts --------
map  ctrl+shift+up     neighboring_window  up
map  ctrl+shift+down   neighboring_window  down
map  ctrl+shift+left   neighboring_window  left
map  ctrl+shift+right  neighboring_window  right
map  ctrl+alt+enter    launch              --cwd=current 
map  alt+t             set_tab_title
map  alt+r             start_resizing_window
map  alt+1             goto_tab            1
map  alt+2             goto_tab            2
map  alt+3             goto_tab            3
map  alt+4             goto_tab            4
map  alt+5             goto_tab            5
map  alt+6             goto_tab            6
map  alt+7             goto_tab            7
map  alt+8             goto_tab            8
map  alt+9             goto_tab            9
map  f7                layout_action       rotate
map  f6                next_layout
