#!/usr/bin/env bash
# ==============================================================================
# Hyprland Multi-Monitor Workspace Manager
# ==============================================================================

set -euo pipefail

# --- Configuration ---
readonly OFFSET_SIZE=100
readonly MAX_WORKSPACES_PER_MONITOR=99
readonly CONFIG_FILE="$HOME/.config/hypr/workspaces.conf"

# --- Helper Functions ---
log_error() {
    echo "ERROR: $*" >&2
}

log_info() {
    echo "$*"
}

get_monitors_ordered() {
    hyprctl monitors -j | jq -r 'sort_by(.x) | .[].name'
}

get_focused_monitor() {
    hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .name'
}

get_monitor_index() {
    local monitor_name="$1"
    local monitors_json
    monitors_json=$(hyprctl monitors -j)

    local index
    index=$(echo "$monitors_json" | jq -r \
        --arg mon "$monitor_name" \
        'sort_by(.x) | map(.name) | index($mon) // 0')

    echo "${index:-0}"
}

calculate_offset() {
    local monitor_index="$1"
    echo $((monitor_index * OFFSET_SIZE))
}

get_current_workspace_id() {
    hyprctl activeworkspace -j | jq -r '.id'
}

wait_for_hyprland() {
    local max_attempts=30
    local attempt=0

    while ((attempt < max_attempts)); do
        if hyprctl monitors -j &>/dev/null; then
            local monitor_count
            monitor_count=$(hyprctl monitors -j | jq 'length')

            if ((monitor_count > 0)); then
                log_info "✓ Hyprland ready with $monitor_count monitor(es)"
                return 0
            fi
        fi

        ((attempt++))
        sleep 0.5
    done

    log_error "Timeout waiting for Hyprland"
    return 1
}

check_source_exists() {
    local hyprland_conf="$HOME/.config/hypr/hyprland.conf"

    if [[ ! -f "$hyprland_conf" ]]; then
        return 1
    fi

    # 1. Get the filename only (e.g., workspaces.conf)
    local config_basename
    config_basename=$(basename "$CONFIG_FILE")

    # 2. Get the path relative to HOME (e.g., .config/hypr/workspaces.conf)
    local relative_path="${CONFIG_FILE#$HOME/}"

    # Search for the line, ignoring comments, matching:
    # - The full absolute path
    # - The path starting with ~/
    # - Or just the specific config filename in a known path
    grep -v '^[[:space:]]*#' "$hyprland_conf" 2>/dev/null |
        grep -qE "source[[:space:]]*=[[:space:]]*.*(~/${relative_path}|${CONFIG_FILE}|${config_basename})"
}

add_source_to_config() {
    local hyprland_conf="$HOME/.config/hypr/hyprland.conf"
    local backup_file="${hyprland_conf}.backup-$(date +%Y%m%d-%H%M%S)"

    cp "$hyprland_conf" "$backup_file"

    {
        echo ""
        echo "# Workspace multi-monitor (auto-generated by workspace-manager.sh)"
        echo "source = $CONFIG_FILE"
    } >>"$hyprland_conf"

    log_info "✓ Added to hyprland.conf"
    log_info "✓ Backup created: $backup_file"
}

# --- Modular Initialization ---
init_monitors() {
    log_info "🚀 Initializing workspaces per monitor..."
    log_info ""

    local monitors
    monitors=$(get_monitors_ordered)

    local monitor_count
    monitor_count=$(echo "$monitors" | wc -l)

    log_info "📊 Detected monitors: $monitor_count"

    local temp_config="/tmp/hyprland-workspace-rules-$$.conf"

    cat >"$temp_config" <<'HEADER'
# ==============================================================================
# Hyprland Workspace Rules - Auto-generated
# DO NOT EDIT MANUALLY - IT WILL BE OVERWRITTEN
# ==============================================================================

HEADER

    local -a monitor_array=()
    while IFS= read -r mon; do
        [[ -n "$mon" ]] && monitor_array+=("$mon")
    done <<<"$monitors"

    local -a workspace_list=()

    for idx in "${!monitor_array[@]}"; do
        local monitor="${monitor_array[$idx]}"
        local base_ws=$((idx * OFFSET_SIZE + 1))

        workspace_list+=("$base_ws")
        log_info "  Monitor $idx: $monitor → base workspace $base_ws"

        echo "workspace = $base_ws, monitor:$monitor, default:true" >>"$temp_config"

        local ws_start=$((idx * OFFSET_SIZE + 1))
        for offset in $(seq 0 9); do
            local ws=$((ws_start + offset))
            echo "workspace = $ws, monitor:$monitor" >>"$temp_config"
        done
    done

    mkdir -p "$(dirname "$CONFIG_FILE")"
    mv "$temp_config" "$CONFIG_FILE"

    log_info ""
    log_info "✅ Config file generated: $CONFIG_FILE"

    if check_source_exists; then
        log_info "✓ Already configured in hyprland.conf"
    else
        log_info ""
        log_info "📝 Add this line to your hyprland.conf:"
        log_info "    source = $CONFIG_FILE"
        log_info ""

        if [[ -t 0 ]]; then
            read -p "Add automatically? (y/N) " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                add_source_to_config
            fi
        else
            log_info "⚠ Running in non-interactive mode, add manually."
        fi
    fi

    log_info ""
    log_info "Applying workspaces..."

    for idx in "${!monitor_array[@]}"; do
        local mon="${monitor_array[$idx]}"
        local ws="${workspace_list[$idx]}"
        log_info "  Moving $mon → workspace $ws"
        hyprctl --batch "dispatch focusmonitor $mon; dispatch workspace $ws" 2>/dev/null || true
        sleep 0.1
    done

    log_info ""
    log_info "✅ Initialization complete!"
}

auto_update_on_boot() {
    log_info "🔄 Auto-update on boot..."
    if ! wait_for_hyprland; then
        log_error "Failed to wait for Hyprland"
        exit 1
    fi
    sleep 1
    init_monitors
}

# --- Workspace Navigation ---
switch_workspace() {
    local target="$1"
    if ! [[ "$target" =~ ^[0-9]+$ ]] || ((target < 1 || target > MAX_WORKSPACES_PER_MONITOR)); then
        log_error "Workspace $target out of range"
        return 1
    fi

    local focused_monitor=$(get_focused_monitor)
    local monitor_index=$(get_monitor_index "$focused_monitor")
    local base_offset=$(calculate_offset "$monitor_index")
    local target_ws=$((base_offset + target))

    hyprctl dispatch workspace "$target_ws"
}

move_to_workspace() {
    local target="$1"
    if ! [[ "$target" =~ ^[0-9]+$ ]] || ((target < 1 || target > MAX_WORKSPACES_PER_MONITOR)); then
        log_error "Workspace $target out of range"
        return 1
    fi

    local focused_monitor=$(get_focused_monitor)
    local monitor_index=$(get_monitor_index "$focused_monitor")
    local base_offset=$(calculate_offset "$monitor_index")
    local target_ws=$((base_offset + target))

    hyprctl dispatch movetoworkspace "$target_ws"
}

move_to_workspace_silent() {
    local target="$1"
    if ! [[ "$target" =~ ^[0-9]+$ ]] || ((target < 1 || target > MAX_WORKSPACES_PER_MONITOR)); then
        log_error "Workspace $target out of range"
        return 1
    fi

    local focused_monitor=$(get_focused_monitor)
    local monitor_index=$(get_monitor_index "$focused_monitor")
    local base_offset=$(calculate_offset "$monitor_index")
    local target_ws=$((base_offset + target))

    hyprctl dispatch movetoworkspacesilent "$target_ws"
}

navigate() {
    local direction="$1"
    local current_ws=$(get_current_workspace_id)
    local focused_monitor=$(get_focused_monitor)
    local monitor_index=$(get_monitor_index "$focused_monitor")
    local base_offset=$(calculate_offset "$monitor_index")
    local relative_ws=$((current_ws - base_offset))

    if ((relative_ws < 1 || relative_ws > MAX_WORKSPACES_PER_MONITOR)); then
        relative_ws=1
    fi

    local new_relative
    if [[ "$direction" == "next" ]]; then
        new_relative=$((relative_ws + 1))
        ((new_relative > MAX_WORKSPACES_PER_MONITOR)) && return 0
    else
        new_relative=$((relative_ws - 1))
        ((new_relative < 1)) && return 0
    fi

    local target_ws=$((base_offset + new_relative))
    hyprctl dispatch workspace "$target_ws"
}

move_and_navigate() {
    local direction="$1"
    local current_ws=$(get_current_workspace_id)
    local focused_monitor=$(get_focused_monitor)
    local monitor_index=$(get_monitor_index "$focused_monitor")
    local base_offset=$(calculate_offset "$monitor_index")
    local relative_ws=$((current_ws - base_offset))

    if ((relative_ws < 1 || relative_ws > MAX_WORKSPACES_PER_MONITOR)); then
        relative_ws=1
    fi

    local new_relative
    if [[ "$direction" == "next" ]]; then
        new_relative=$((relative_ws + 1))
        ((new_relative > MAX_WORKSPACES_PER_MONITOR)) && return 0
    else
        new_relative=$((relative_ws - 1))
        ((new_relative < 1)) && return 0
    fi

    local target_ws=$((base_offset + new_relative))
    hyprctl dispatch movetoworkspace "$target_ws"
}

status() {
    echo "=== Workspace Manager Status ==="
    echo ""

    local monitors=$(get_monitors_ordered)
    local -a monitor_array=()
    while IFS= read -r mon; do
        [[ -n "$mon" ]] && monitor_array+=("$mon")
    done <<<"$monitors"

    local monitors_json=$(hyprctl monitors -j)

    for idx in "${!monitor_array[@]}"; do
        local monitor="${monitor_array[$idx]}"
        local base_ws=$((idx * OFFSET_SIZE + 1))
        local end_ws=$((idx * OFFSET_SIZE + MAX_WORKSPACES_PER_MONITOR))
        local current_ws=$(echo "$monitors_json" | jq -r --arg mon "$monitor" '.[] | select(.name == $mon) | .activeWorkspace.id')
        local relative=$((current_ws - idx * OFFSET_SIZE))
        local focused=""

        if echo "$monitors_json" | jq -e --arg mon "$monitor" '.[] | select(.name == $mon and .focused == true)' &>/dev/null; then
            focused=" [FOCUSED]"
        fi

        echo "  [$idx] $monitor$focused"
        echo "      Range: $base_ws-$end_ws"
        echo "      Current: $current_ws (relative: $relative)"
        echo ""
    done

    echo "Config file: $CONFIG_FILE"
    [[ -f "$CONFIG_FILE" ]] && echo "  ✓ Exists" || echo "  ✗ Missing (run --init)"

    echo ""
    echo "Source in hyprland.conf:"
    check_source_exists && echo "  ✓ Configured" || echo "  ✗ Not configured (run --init)"
}

main() {
    local action="${1:-}"
    local arg="${2:-}"

    case "$action" in
    --init) init_monitors ;;
    --auto-update) auto_update_on_boot ;;
    --status | status) status ;;
    switch)
        [[ -z "$arg" ]] && {
            log_error "Usage: $0 switch <1-99>"
            exit 1
        }
        switch_workspace "$arg"
        ;;
    move)
        [[ -z "$arg" ]] && {
            log_error "Usage: $0 move <1-99>"
            exit 1
        }
        move_to_workspace "$arg"
        ;;
    movesilent)
        [[ -z "$arg" ]] && {
            log_error "Usage: $0 movesilent <1-99>"
            exit 1
        }
        move_to_workspace_silent "$arg"
        ;;
    next) navigate "next" ;;
    prev) navigate "prev" ;;
    move_next) move_and_navigate "next" ;;
    move_prev) move_and_navigate "prev" ;;
    *)
        echo "Usage: $0 <command> [args]"
        exit 1
        ;;
    esac
}

main "$@"
