# -----------------------------------------------------
# ENVIRONMENT VARIABLES
# -----------------------------------------------------

# --- Hardware ---
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = AQ_FORCE_LINEAR_BLIT,0

# --- XDG / Session ---
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_MENU_PREFIX,arch-

# --- Toolkits (Qt, GTK) ---
env = GTK_THEME,adw-gtk3-dark
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# --- Cursors ---
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,MacOSXyb64
env = HYPRCURSOR_THEME,MacOSXyb64
env = HYPRCURSOR_SIZE,24

# --- PATH ---
env = PATH,$HOME/.local/bin:$PATH

# --- Scripts & Apps ---
# Defines where hyprshot will save (if your script reads this variable)
env = HYPRSHOT_DIR,$HOME/Pictures/Screenshots
