#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = latam
    kb_variant = 
    repeat_delay = 250
    kb_model =
    kb_options =
    kb_rules =

    force_no_accel = true

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

device {
    name = at-translated-set-2-keyboard
    enabled = false
}

# cursor {
#     no_hardware_cursors = false
# }
